"""
syn_ack_spoofer.py
-------------------
Intercepts outgoing SYN-ACK packets from port 102 using netfilter queue
and rewrites two fields that `fingerprint_harden.sh`'s sysctl approach
cannot reach:

    1. TCP window size -- Linux defaults to 64KB+, embedded RTOS stacks
       typically use 1024-4096. Nmap's OS detection and p0f both key on
       this heavily.

    2. TCP options in the SYN-ACK -- Linux includes SACK, timestamps,
       and window-scale options by default; these are disabled for
       subsequent packets by sysctl (in fingerprint_harden.sh), but the
       SYN-ACK itself is generated by the kernel before sysctl takes
       full effect on option negotiation. We strip it to MSS-only, which
       is the minimal embedded-stack pattern.

These two changes together make Nmap's -O OS detection and passive
fingerprinters like p0f classify the host as an embedded device rather
than a Linux box, closing the gap fingerprint_harden.sh can't reach.

SETUP (done by fingerprint_harden.sh apply):
    sudo apt install -y python3-netfilterqueue
    iptables -I OUTPUT -p tcp --sport 102 \\
        --tcp-flags SYN,ACK SYN,ACK \\
        -j NFQUEUE --queue-num 42 \\
        -m comment --comment s7honeypot-synack-spoof

    Then run this script as root (or with CAP_NET_ADMIN):
    sudo python3 /opt/s7honeypot/syn_ack_spoofer.py

CONFIRMED SIEMENS-LIKE VALUES (from published ICS fingerprinting
research and Nmap OS database embedded-device entries):
    Window size: 1024 -- standard small-stack RTOS value
    TCP options: MSS=1452 only (no SACK, timestamps, window scale)
    Data offset: 6 (20 byte TCP base + 4 byte MSS option = 24 bytes)

This does NOT affect the TCP connection itself -- the kernel's TCP state
machine still handles everything correctly. We are only modifying what
we ADVERTISE in the SYN-ACK; the kernel will operate within those
advertised parameters.

NO SCAPY DEPENDENCY -- pure struct-based packet manipulation with a
tested Internet checksum implementation. The only external dependency
is python3-netfilterqueue (C extension, available via apt on Debian).
"""

from __future__ import annotations

import logging
import os
import signal
import struct
import sys

log = logging.getLogger("syn_ack_spoofer")


# ---------- Configurable Siemens-like SYN-ACK parameters ---------------

TARGET_WINDOW  = 1024   # bytes -- typical embedded RTOS TCP stack value
TARGET_MSS     = 1452   # bytes -- common on 100Mbps Ethernet embedded devices
NFQUEUE_NUM    = 42     # must match the iptables rule in fingerprint_harden.sh


# ---------- Checksum (RFC 1071) -----------------------------------------

def _checksum(data: bytes) -> int:
    """
    Standard Internet checksum (RFC 1071) used for both IP and TCP.
    Handles odd-length data by zero-padding. Returns the 16-bit ones-
    complement sum.
    """
    if len(data) % 2:
        data += b"\x00"
    s = sum(struct.unpack_from(f">{len(data)//2}H", data))
    while s >> 16:
        s = (s & 0xFFFF) + (s >> 16)
    return ~s & 0xFFFF


# ---------- Packet modification -----------------------------------------

def _build_mss_option(mss: int) -> bytes:
    """MSS TCP option: kind=2, len=4, value (2 bytes big-endian)."""
    return struct.pack(">BBH", 2, 4, mss)


def rewrite_syn_ack(payload: bytes) -> bytes | None:
    """
    Parse an IP packet, verify it's a TCP SYN-ACK from port 102,
    rewrite window size and TCP options, recalculate both checksums,
    and return the modified packet.

    Returns None if the packet should be passed unmodified (not a
    SYN-ACK from port 102, or parse failed).

    Packet structure (no Ethernet header -- NFQUEUE OUTPUT hook):
        IP header  (IHL * 4 bytes, typically 20)
        TCP header (data_offset * 4 bytes, min 20)
    """
    if len(payload) < 40:  # absolute minimum: 20 IP + 20 TCP
        return None

    # ---- IP header ----
    ip_ihl = (payload[0] & 0x0F) * 4
    if payload[9] != 6:         # not TCP
        return None
    if len(payload) < ip_ihl + 20:
        return None

    src_ip = payload[12:16]
    dst_ip = payload[16:20]

    # ---- TCP header ----
    tcp = payload[ip_ihl:]
    src_port = struct.unpack_from(">H", tcp, 0)[0]
    if src_port != 102:
        return None

    flags = tcp[13]
    SYN = 0x02
    ACK = 0x10
    if (flags & (SYN | ACK)) != (SYN | ACK):
        return None  # not a SYN-ACK

    seq_num = tcp[4:8]
    ack_num = tcp[8:12]
    dst_port_bytes = tcp[2:4]
    urg = tcp[18:20]

    # ---- Build replacement TCP options ----
    new_options = _build_mss_option(TARGET_MSS)
    # Pad to 4-byte boundary (already aligned at 4 bytes for MSS option)
    while len(new_options) % 4 != 0:
        new_options += b"\x00"

    new_tcp_header_len = 20 + len(new_options)
    data_offset_nibble = (new_tcp_header_len // 4) << 4

    # ---- Assemble new TCP header (checksum zeroed for calculation) ----
    new_tcp = (
        struct.pack(">H", src_port)           # src port
        + dst_port_bytes                       # dst port
        + seq_num                              # seq
        + ack_num                              # ack
        + bytes([data_offset_nibble, flags])   # data offset + flags
        + struct.pack(">H", TARGET_WINDOW)     # window size (rewritten)
        + b"\x00\x00"                          # checksum (placeholder)
        + urg                                  # urgent pointer
        + new_options                          # options (rewritten)
    )

    # ---- TCP pseudo-header for checksum ----
    pseudo = src_ip + dst_ip + b"\x00\x06" + struct.pack(">H", len(new_tcp))
    tcp_checksum = _checksum(pseudo + new_tcp)

    # Insert computed checksum at byte 16 of TCP header
    new_tcp = new_tcp[:16] + struct.pack(">H", tcp_checksum) + new_tcp[18:]

    # ---- Rebuild IP header with updated total length ----
    new_total_len = ip_ihl + len(new_tcp)
    ip_header = bytearray(payload[:ip_ihl])
    struct.pack_into(">H", ip_header, 2, new_total_len)  # total length
    ip_header[10] = 0   # zero checksum before recalculation
    ip_header[11] = 0
    ip_checksum = _checksum(bytes(ip_header[:ip_ihl]))
    struct.pack_into(">H", ip_header, 10, ip_checksum)

    result = bytes(ip_header) + new_tcp
    return result


# ---------- NFQUEUE callback -------------------------------------------

def _make_callback(stats: dict):
    def callback(packet) -> None:
        payload = packet.get_payload()
        modified = rewrite_syn_ack(payload)
        if modified is not None:
            packet.set_payload(modified)
            stats["modified"] += 1
            log.debug("Rewrote SYN-ACK: window=%d MSS=%d", TARGET_WINDOW, TARGET_MSS)
        packet.accept()
    return callback


# ---------- Main -----------------------------------------------------------

def run() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    if os.geteuid() != 0:
        log.error("Must run as root (or with CAP_NET_ADMIN) to use NFQUEUE")
        sys.exit(1)

    try:
        import netfilterqueue
    except ImportError:
        log.error(
            "python3-netfilterqueue not installed. "
            "Run: sudo apt install -y python3-netfilterqueue"
        )
        sys.exit(1)

    stats = {"modified": 0}
    nfq = netfilterqueue.NetfilterQueue()
    nfq.bind(NFQUEUE_NUM, _make_callback(stats))

    log.info(
        "SYN-ACK spoofer active: queue=%d window=%d MSS=%d "
        "(iptables must route port-102 SYN-ACKs to this queue -- "
        "run fingerprint_harden.sh apply if not already done)",
        NFQUEUE_NUM, TARGET_WINDOW, TARGET_MSS,
    )

    def _shutdown(sig, frame):
        log.info("Shutting down (modified %d SYN-ACK packets)", stats["modified"])
        nfq.unbind()
        sys.exit(0)

    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    try:
        nfq.run()
    except Exception as e:
        log.error("NFQUEUE error: %s", e)
        nfq.unbind()
        raise


if __name__ == "__main__":
    run()
